### ISSUE TITLE
Issues with Babele

### ISSUE THREAD

**Issue by Bryn1701** [pchouzenoux/foundryvtt-dnd5-cheatsheet#11]
After the last few weeks I have been having errors regarding Babele. I don't use the module myself, but since it's a dependency for this module I was curious if there was a way to disconnect the reliability on Babele somewhere? Like an option to have it as a dependency or not ?

Thanks for the great mod!

**Comment by pchouzenoux** [comment]
Hi @Bryn1701,

`babele` dependency is used to support translations (French translation are included in this mod), if you are playing in english you don't care about this dependencies. Unfortunately you cannot disable it because FoundryVTT force dependencies to be enabled.

But I will keep this issue open, because I probably can remove `babele` loading at start or split in two mods.

Happy to see that people use this mod :) My players always forget to check this helps !!!

**Comment by pchouzenoux** [comment]
This issue was closed because it has been inactive for a long time.
