### ISSUE TITLE
Module does not show up inside game

### ISSUE THREAD

**Issue by deraviin** [pchouzenoux/foundryvtt-dnd5-cheatsheet#5]
This module does not show up inside the world to be activated. Foundry version 0.7.10, dnd5e version 1.2.4

**Comment by pchouzenoux** [comment]
Hi @deraviin,

I did a mistake in module configuration that created a mess in downloads, so since I published the version for Foundry 0.8.6 no one was able to install another version that the new one.

I fixed that by redeploying the correct config for versions 0.0.3 (for foundry 0.7.X) and 0.0.4 (for foundry 0.8.X).

So please uninstall the module and reinstall it from FoundryVTT module manager and it should work.

Let me know if you still have trouble with it.
