### ISSUE TITLE
Feature: Allow GM's to input their own icons/content

### ISSUE THREAD

**Issue by Bryn1701** [pchouzenoux/foundryvtt-dnd5-cheatsheet#8]
As the title says. I would love the ability to add my own icons and content to the 4 buttons of information. This would allow  home brew rules to be added but also would also other systems other than D&D cheat sheets to be created. I know you have given information how to make you own, but for those less tech savvy(me included) this could be a way to make changes.

Thanks again for a great module!

**Comment by pchouzenoux** [comment]
Hi @Bryn1701 

Glad to ear that you love this little module.

I started to work on the enhancement you proposed. It's interesting but I some part of the feature are more complexe to put in place.

For example, custom the icon is hard because Foundry use a preset of icon that we can use. So I can open a configuration to select one in this list, but it's not super customizable. List of icons is quite huge: https://fontawesome.com/v5.15/icons?d=gallery&p=2&m=free.

Work is still in progress but currently I added a configuration panel that will look like that:

![Capture d’écran, le 2021-06-28 à 17 59 58](https://user-images.githubusercontent.com/2341983/123709653-6854f380-d83b-11eb-8fe3-f346987d03ae.png)

![Capture d’écran, le 2021-06-28 à 18 00 07](https://user-images.githubusercontent.com/2341983/123709662-6be87a80-d83b-11eb-986a-ceb4fa06d7d8.png)

PS: It's not releasable yet I need to work on the UI to have something usable :)

**Comment by Bryn1701** [comment]
Looks great! Can't wait to give it a whirl!

**Comment by pchouzenoux** [comment]
This new feature is now live with version `0.0.6`.

 I also added a section in the README to add more explanations about how to configure it: https://github.com/pchouzenoux/foundryvtt-dnd5-cheatsheet#how-to-configure.

Have fun !

**Comment by Bryn1701** [comment]
Amazing! Thank you!! Cant wait to get my homebrew info into this!
